export const ABNORMALITY_FETCH_REQUEST = "ABNORMALITY_FETCH_REQUEST";
export const ABNORMALITY_FETCH_SUCCESS = "ABNORMALITY_FETCH_SUCCESS";
export const ABNORMALITY_FETCH_FAIL = "ABNORMALITY_FETCH_FAIL";
