export const PENDING_TASK_FETCH_REQUEST = "PENDING_TASK_FETCH_REQUEST";
export const PENDING_TASK_FETCH_SUCCESS = "PENDING_TASK_FETCH_SUCCESS";
export const PENDING_TASK_FETCH_FAIL = "PENDING_TASK_FETCH_FAIL";
