export const DAILYSTATUS_FETCH_REQUEST = "DAILYSTATUS_FETCH_REQUEST";
export const DAILYSTATUS_FETCH_SUCCESS = "DAILYSTATUS_FETCH_SUCCESS";
export const DAILYSTATUS_FETCH_FAIL = "DAILYSTATUS_FETCH_FAIL";
